# Generated by Django 6.0.6 on 2026-06-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='parse_log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('partial', 'Partial — some lines unparsed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
