# Generated by Django 6.0.6 on 2026-06-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tin', models.CharField(blank=True, max_length=50, verbose_name='No de transitaire/TIN/IDE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
