# Generated by Django 6.0.6 on 2026-06-25 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tariff', '0003_alter_tariffcode_text_de_alter_tariffcode_text_fr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('llm', 'LLM-suggested, confirmed'), ('auto', 'Auto-accepted, high confidence')], default='manual', max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='customers.customer')),
                ('tariff_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='tariff.tariffcode')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tariff_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tariff.tariffcode')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='catalog.sku')),
            ],
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['customer', 'article_code'], name='catalog_sku_custome_dbf509_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sku',
            unique_together={('customer', 'article_code')},
        ),
    ]
