# Generated by Django 6.0.6 on 2026-06-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_alter_tariffcode_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffcode',
            name='text_de',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tariffcode',
            name='text_fr',
            field=models.TextField(),
        ),
    ]
